### ISSUE TITLE
[JOSS review] Installation issues

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [BlauGroup/RNMC#12]
Hi! This is an issue that's part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/7244)

I'm trying to build the software on my computer, which runs Ubuntu 22.04. Unfortunately, linking fails with a bunch of `undefined reference to sqlite3_[...]` errors. Note that the packages `sqlite3`, `libsqlite3-dev` and `libsqlite3-0` are all installed. Can you help me?

More in general, I think that it would be nice if you could devise a better way of installing the software than just makefiles. My advice is to consider using cmake (or even the venerable configure) to manage the pre-compilation and compilation stages.

**Comment by espottesmith** [comment]
Hey Lorenzo,

Thank you for raising this issue. We're trying to diagnose what's going on. For us to reproduce the issue, it'd be helpful if you could give us some more information. Specifically, the following would be helpful:

1. Full error messages
2. Your `LIBRARY_PATH` and/or `LD_LIBRARY_PATH`.

We're also looking into changing our build process to use `cmake`, though, if we can resolve this issue and make our makefiles more robust, we may keep with our current installation method.

**Comment by lorenzo-rovigatti** [comment]
Sure thing! Here is the output of `build.sh`: [errors.txt](https://github.com/user-attachments/files/17293330/errors.txt)
Both env variables are empty. Note that the following program compiles with `g++ -o sql sql.cpp -lsqlite3`:

```C++
#include <iostream> 
#include <sqlite3.h> 
  
int main(int argc, char** argv) 
{ 
    sqlite3* DB; 
    int exit = 0; 
    exit = sqlite3_open("example.db", &DB); 
  
    if (exit) { 
        std::cerr << "Error open DB " << sqlite3_errmsg(DB) << std::endl; 
        return (-1); 
    } 
    else
        std::cout << "Opened Database Successfully!" << std::endl; 
    sqlite3_close(DB); 
    return (0); 
}
```

**Comment by espottesmith** [comment]
Thanks for that detail! I believe this should have been fixed by https://github.com/BlauGroup/RNMC/pull/16. Please check and see if you can install now.

**Comment by lorenzo-rovigatti** [comment]
It works now, thank you!
