### ISSUE TITLE
[JOSS review] Some information missing

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [BlauGroup/RNMC#13]
Hi! This is an issue that's linked to the [JOSS review](https://github.com/openjournals/joss-reviews/issues/7244)

According to the JOSS guidelines, there should be clear guidelines for third parties wishing to 

1. Contribute to the software 
2. Report issues or problems with the software 
3. Seek support

As far as I can see these are all missing in the current version of the repo. My advice is to set up [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for n. 2, and to add to the README and/or to the docs some information about what people should do to contribute to your software.

**Comment by ptmerz** [comment]
Other reviewer here. I'll note that https://blaugroup.github.io/RNMC/ does have a section which covers the three points listed above. I think this is technically sufficient to pass the JOSS requirement, but I agree with @lorenzo-rovigatti that having these things mirrored on the repo README would be valuable!

**Comment by espottesmith** [comment]
Good suggestion! We'll provide a briefer description of these points in the README

**Comment by espottesmith** [comment]
@lorenzo-rovigatti @ptmerz, please check the README now. If you're satisfied, I'll close this issue.

**Comment by lorenzo-rovigatti** [comment]
I think that's enough to comply with JOSS's requirements. I close this one, thank you!
